import csv
from collections import defaultdict
from datetime import date, datetime
from pathlib import Path

import streamlit as st
from src.graph import plot_amount_over_time, plot_category_pie, plot_category_totals

DATA_PATH = Path(__file__).resolve().parent / "data" / "gold_certified_data.csv"
DATE_FORMAT = "%Y-%m-%d"


def apply_theme(is_dark: bool):
    if is_dark:
        css = """
        <style>
            [data-testid="stAppViewContainer"] { background-color: #111827; }
            [data-testid="stHeader"] { background-color: rgba(17, 24, 39, 0.8); }
            [data-testid="stSidebar"] { background-color: #1F2937; }
            h1, h2, h3, h4, p, label, .stMarkdown, .stText { color: #F9FAFB !important; }
            div[data-testid="stMetricValue"], div[data-testid="stMetricLabel"] { color: #F9FAFB !important; }
            div[data-testid="stVerticalBlockBorderWrapper"] { border-color: #374151 !important; border-radius: 12px; background-color: #1F2937; }
            .stDataFrame { border-radius: 8px; }
            [data-baseweb="select"] > div { background-color: #374151; color: white; }
        </style>
        """
    else:
        css = """
        <style>
            [data-testid="stAppViewContainer"] { background-color: #F3F4F6; }
            [data-testid="stHeader"] { background-color: rgba(243, 244, 246, 0.8); }
            [data-testid="stSidebar"] { background-color: #FFFFFF; }
            h1, h2, h3, h4, p, label, .stMarkdown, .stText { color: #111827 !important; }
            div[data-testid="stMetricValue"], div[data-testid="stMetricLabel"] { color: #111827 !important; }
            div[data-testid="stVerticalBlockBorderWrapper"] { border-color: #E5E7EB !important; border-radius: 12px; background-color: #FFFFFF; }
            .stDataFrame { border-radius: 8px; }
        </style>
        """
    st.markdown(css, unsafe_allow_html=True)


def parse_date(value: str):
    try:
        return datetime.strptime(value, DATE_FORMAT).date()
    except (TypeError, ValueError):
        return None


def load_data(path: Path):
    with path.open(newline="", encoding="utf-8") as fp:
        reader = csv.DictReader(fp)
        rows = list(reader)

    for row in rows:
        if "amount" in row:
            try:
                row["amount"] = float(row["amount"])
            except (ValueError, TypeError):
                pass
        if "confidence" in row:
            try:
                row["confidence"] = float(row["confidence"])
            except (ValueError, TypeError):
                pass
        row["parsed_date"] = parse_date(row.get("date"))
    return rows


def render_dashboard(data, is_dark: bool):
    st.title("💸 Financial Dashboard")
    st.markdown("Monitor and analyze your spending trends with advanced analytics.", unsafe_allow_html=True)

    # Calculate KPIs
    valid_amounts = [row.get("amount", 0) for row in data if isinstance(row.get("amount"), (int, float))]
    total_amount = sum(valid_amounts)
    num_tx = len(data)
    
    cat_totals = defaultdict(float)
    for row in data:
        amount = row.get("amount")
        cat = row.get("category")
        if cat and isinstance(amount, (int, float)):
             cat_totals[cat] += amount
    top_cat = max(cat_totals.items(), key=lambda x: x[1])[0] if cat_totals else "N/A"

    # Display KPI Metrics
    with st.container(border=True):
        col1, col2, col3 = st.columns(3)
        col1.metric("Total Spending", f"€ {total_amount:,.2f}")
        col2.metric("Total Transactions", num_tx)
        col3.metric("Top Category", top_cat)

    st.markdown("<br>", unsafe_allow_html=True)

    # Category Charts Options
    chart_type = st.radio("Select Category Overview type", ["Bar Chart", "Donut Chart"], horizontal=True)
    if chart_type == "Donut Chart":
        chart = plot_category_pie(data, is_dark=is_dark)
    else:
        chart = plot_category_totals(data, is_dark=is_dark)

    # Layout for charts
    col1, col2 = st.columns(2)
    with col1:
        with st.container(border=True):
            st.plotly_chart(chart, use_container_width=True)

    with col2:
        with st.container(border=True):
            st.plotly_chart(plot_amount_over_time(data, is_dark=is_dark), use_container_width=True)

    st.caption("Insights generated by Auto-BI Assistant.")


def render_table(data):
    st.title("🗂️ Data Explorer")
    st.markdown("Filter and view your raw certified data.")

    categories = sorted({row.get("category", "") for row in data if row.get("category", "")})
    categories.insert(0, "All")

    dates = [row.get("parsed_date") for row in data if row.get("parsed_date") is not None]
    min_date = min(dates) if dates else date.today()
    max_date = max(dates) if dates else date.today()

    today = date.today()
    start_of_year = date(today.year, 1, 1)
    default_start = max(start_of_year, min_date)
    default_end = min(today, max_date)

    with st.container(border=True):
        st.subheader("Filters")
        filter_col1, filter_col2 = st.columns((2, 3))
        selected_categories = filter_col1.multiselect("Category", categories, default=["All"])
        selected_dates = filter_col2.date_input(
            "Date range",
            value=(default_start, default_end),
            min_value=min_date,
            max_value=max_date,
        )

    if isinstance(selected_dates, tuple):
        selected_dates = list(selected_dates)

    if isinstance(selected_dates, list) and len(selected_dates) == 2:
        start_date, end_date = selected_dates
    else:
        start_date = end_date = selected_dates

    filtered = data
    if selected_categories and "All" not in selected_categories:
        filtered = [row for row in filtered if row.get("category") in selected_categories]

    filtered = [
        row
        for row in filtered
        if row.get("parsed_date") is not None and start_date <= row["parsed_date"] <= end_date
    ]

    st.write(f"**Showing {len(filtered)} of {len(data)} transactions**")
    
    st.dataframe(
        filtered,
        use_container_width=True,
        hide_index=True,
        column_config={
            "parsed_date": st.column_config.DateColumn("Date", format="DD/MM/YYYY"),
            "amount": st.column_config.NumberColumn("Amount", format="€ %.2f"),
            "confidence": st.column_config.ProgressColumn("Confidence", min_value=0, max_value=1, format="%.2f"),
        }
    )


def main():
    st.set_page_config(page_title="Personal BI Assistant", page_icon="📈", layout="wide")

    # Sidebar settings
    st.sidebar.title("Navigation")
    page = st.sidebar.radio("Go to", ["📊 Dashboard", "📋 Table"])
    
    st.sidebar.markdown("---")
    
    # Theme Toggle
    if "dark_mode" not in st.session_state:
        st.session_state.dark_mode = True # Default to dark mode
    
    is_dark = st.sidebar.toggle("🌙 Dark Mode", value=st.session_state.dark_mode)
    st.session_state.dark_mode = is_dark
    
    apply_theme(is_dark)

    if not DATA_PATH.exists():
        st.sidebar.error(f"File not found: {DATA_PATH}")
        return

    data = load_data(DATA_PATH)
    if not data:
        st.sidebar.warning("The file exists but does not contain rows to display.")
        return

    if page == "📊 Dashboard":
        render_dashboard(data, is_dark)
    else:
        render_table(data)


if __name__ == "__main__":
    main()
