import csv
from datetime import date, datetime
from pathlib import Path

import streamlit as st
from src.graph import plot_amount_over_time, plot_category_pie, plot_category_totals

DATA_PATH = Path(__file__).resolve().parent / "data" / "gold_certified_data.csv"
DATE_FORMAT = "%Y-%m-%d"


def parse_date(value: str):
    try:
        return datetime.strptime(value, DATE_FORMAT).date()
    except (TypeError, ValueError):
        return None



def load_data(path: Path):
    with path.open(newline="", encoding="utf-8") as fp:
        reader = csv.DictReader(fp)
        rows = list(reader)

    for row in rows:
        if "amount" in row:
            try:
                row["amount"] = float(row["amount"])
            except (ValueError, TypeError):
                pass
        if "confidence" in row:
            try:
                row["confidence"] = float(row["confidence"])
            except (ValueError, TypeError):
                pass
        row["parsed_date"] = parse_date(row.get("date"))
    return rows


def render_dashboard(data):
    st.header("Dashboard")
    st.markdown("Charts generated by `src/graph.py`.")

    chart_type = st.radio("Chart type for categories", ["Bar", "Pie"], horizontal=True)
    if chart_type == "Pie":
        chart = plot_category_pie(data)
    else:
        chart = plot_category_totals(data)

    col1, col2 = st.columns(2)
    with col1:
        st.subheader("Total amount by category")
        st.plotly_chart(chart, width="stretch")

    with col2:
        st.subheader("Total amount by day")
        st.plotly_chart(plot_amount_over_time(data), width="stretch")

    st.markdown("---")
    st.write(
        "Here you can view payment trends and identify the categories with the highest spending volume."
    )


def render_table(data):
    st.header("Table")
    st.markdown("Display all `gold_certified_data.csv` data in a full-width table.")

    categories = sorted({row.get("category", "") for row in data if row.get("category", "")})
    categories.insert(0, "All")

    dates = [row.get("parsed_date") for row in data if row.get("parsed_date") is not None]
    min_date = min(dates) if dates else date.today()
    max_date = max(dates) if dates else date.today()

    today = date.today()
    start_of_year = date(today.year, 1, 1)
    default_start = max(start_of_year, min_date)
    default_end = min(today, max_date)

    filter_col1, filter_col2 = st.columns((2, 3))
    selected_categories = filter_col1.multiselect("Category", categories, default=["All"])
    selected_dates = filter_col2.date_input(
        "Date range",
        value=(default_start, default_end),
        min_value=min_date,
        max_value=max_date,
    )

    if isinstance(selected_dates, tuple):
        selected_dates = list(selected_dates)

    if isinstance(selected_dates, list) and len(selected_dates) == 2:
        start_date, end_date = selected_dates
    else:
        start_date = end_date = selected_dates

    filtered = data
    if selected_categories and "All" not in selected_categories:
        filtered = [row for row in filtered if row.get("category") in selected_categories]

    filtered = [
        row
        for row in filtered
        if row.get("parsed_date") is not None and start_date <= row["parsed_date"] <= end_date
    ]

    st.write(f"Rows shown: {len(filtered)} of {len(data)}")
    st.dataframe(filtered, width="stretch")


def main():
    st.set_page_config(page_title="Gold Certified Data", layout="wide")

    page = st.sidebar.radio("Select page", ["Dashboard", "Table"])

    if not DATA_PATH.exists():
        st.sidebar.error(f"File not found: {DATA_PATH}")
        return

    data = load_data(DATA_PATH)
    if not data:
        st.sidebar.warning("The file exists but does not contain rows to display.")
        return

    if page == "Dashboard":
        render_dashboard(data)
    else:
        render_table(data)


if __name__ == "__main__":
    main()
