"""add_pgvector_embeddings

Revision ID: 39b16654eccd
Revises: 7c0e46496b84
Create Date: 2026-04-27 22:57:37.563242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = '39b16654eccd'
down_revision: Union[str, Sequence[str], None] = '7c0e46496b84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('merchants', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=2048), nullable=True))
    op.add_column('transactions', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=2048), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'embedding')
    op.drop_column('merchants', 'embedding')
    # ### end Alembic commands ###
