"""fix_embedding_dim

Revision ID: 4423075ffe82
Revises: a328eb179ab2
Create Date: 2026-04-27 23:26:07.574027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = '4423075ffe82'
down_revision: Union[str, Sequence[str], None] = 'a328eb179ab2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('merchants', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=2048),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=1024),
               existing_nullable=True)
    op.alter_column('transactions', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=2048),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=1024),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1024),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=2048),
               existing_nullable=True)
    op.alter_column('merchants', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1024),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=2048),
               existing_nullable=True)
    # ### end Alembic commands ###
