"""add_regex_rules_table

Revision ID: a328eb179ab2
Revises: 39b16654eccd
Create Date: 2026-04-27 23:07:58.179855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a328eb179ab2'
down_revision: Union[str, Sequence[str], None] = '39b16654eccd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regex_rules',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('pattern', sa.String(), nullable=True),
    sa.Column('merchant_name', sa.String(), nullable=True),
    sa.Column('category_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pattern')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('regex_rules')
    # ### end Alembic commands ###
