import streamlit as st
from collections import defaultdict
from auto_bi.utils.graph import plot_amount_over_time, plot_category_pie, plot_category_totals

def render_dashboard(data):
    st.markdown("<h2 style='text-align: center;'>📈 Dashboard</h2>", unsafe_allow_html=True)
    
    # Separate Outgoing and Incoming (with backward compatibility)
    outgoing = [abs(row.get("amount", 0)) for row in data if row.get("tipology") in ["Outgoing", "Expense"]]
    incoming = [abs(row.get("amount", 0)) for row in data if row.get("tipology") in ["Incoming", "Salary", "Refund"]]
    
    total_outgoing = sum(outgoing)
    total_incoming = sum(incoming)
    num_tx = len(data)
    
    cat_totals = defaultdict(float)
    for row in data:
        tipology = row.get("tipology", row.get("direction"))
        if tipology not in ("Outgoing", "Expense"):
            continue
        amount = row.get("amount")
        cat = row.get("category")
        if cat and isinstance(amount, (int, float)):
             cat_totals[cat] += abs(amount)
    top_cat = max(cat_totals.items(), key=lambda x: x[1])[0] if cat_totals else "N/A"

    # Net Balance Widget
    balance = total_incoming - total_outgoing
    st.markdown(f"""
        <div style='background-color: #1F2937; padding: 6px 15px; border-radius: 12px; border: 1px solid #374151; margin-bottom: 12px; display: flex; align-items: center; justify-content: center; gap: 20px;'>
            <span style='margin: 0; font-size: 0.8rem; color: #9CA3AF; text-transform: uppercase; font-weight: 600;'>Net Balance</span>
            <span style='margin: 0; color: {"#10B981" if balance >=0 else "#EF4444"}; font-size: 1.6rem; font-weight: bold;'>€ {balance:,.2f}</span>
        </div>
    """, unsafe_allow_html=True)

    with st.container(border=True):
        col1, col2, col3, col4 = st.columns(4)
        col1.metric("Transactions", num_tx)
        col2.metric("Incoming", f"€ {total_incoming:,.2f}", delta_color="normal")
        col3.metric("Outgoing", f"€ {total_outgoing:,.2f}", delta_color="inverse")
        col4.metric("Top Category", top_cat)

    # Low Confidence Warning
    low_conf_count = len([row for row in data if row.get("confidence", 1.0) < 0.7])
    if low_conf_count > 0:
        st.warning(f"⚠️ **{low_conf_count} transactions** require your review (Confidence < 70%). Switch to the **Table** view and use the 'Needs Review' filter.")

    st.markdown("<br>", unsafe_allow_html=True)

    g_col1, g_col2, g_col3 = st.columns([1,1,1])
    if "time_freq" not in st.session_state:
        st.session_state["time_freq"] = "M"
        
    freq = st.session_state["time_freq"]
    with g_col1:
        if st.button("Daily", width="stretch", type="primary" if freq=="D" else "secondary"):
            st.session_state["time_freq"] = "D"
            st.rerun()
    with g_col2:
        if st.button("Weekly", width="stretch", type="primary" if freq=="W" else "secondary"):
            st.session_state["time_freq"] = "W"
            st.rerun()
    with g_col3:
        if st.button("Monthly", width="stretch", type="primary" if freq=="M" else "secondary"):
            st.session_state["time_freq"] = "M"
            st.rerun()

    st.markdown("<h3 style='text-align: center;'>Cumulative Salary vs Expenses</h3>", unsafe_allow_html=True)
    with st.container(border=True):
        st.plotly_chart(plot_amount_over_time(data, freq=st.session_state["time_freq"]), width="stretch", key="chart_over_time")

    st.markdown("<h3 style='text-align: center;'>Expenses by Category</h3>", unsafe_allow_html=True)
    with st.container(border=True):
        st.plotly_chart(plot_category_pie(data), width="stretch", key="chart_category_pie")

    st.markdown("<h3 style='text-align: center;'>Total Amount by Category</h3>", unsafe_allow_html=True)
    with st.container(border=True):
        st.plotly_chart(plot_category_totals(data), width="stretch", key="chart_category_totals")

    st.caption("Insights generated by Auto-BI Assistant.")
